import "~/styles/globals.css";

import { Input } from "~/components/ui/input";
import { Button } from "~/components/ui/button";
import SignInButton from "~/components/client/SignInButton";
import { Inter } from "next/font/google";
import { getServerAuthSession } from "~/server/auth";
import { NavigationMenu } from "~/components/custom/navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession()
    .then((data) => data)
    .catch((err) => console.error(err));

  if (!session?.user) {
    return (
      <div>
        <Button />
        <h1>need to login</h1>
      </div>
    );
  }

  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <div className="border-b-solid mx-[2.5vw] mb-2 flex items-center justify-between border-b-[1px] border-b-[#e5e7eb] py-1 pr-2">
          <div className="flex items-center gap-4 pl-0">
            <Button variant={"ghost"} className="">
              ManageRM
            </Button>
          </div>
          <div className="flex items-center gap-4">
            <NavigationMenu />
            <Input
              size={24}
              className="h-8 rounded-sm"
              type="text"
              placeholder="Search"
            />
            <SignInButton session={session} />
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
